### ISSUE TITLE
Suggestion: use Roxygen2

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/nLTT#10]
Hadley Wickham's book `R Packages` suggests to use Roxygen2 for documentation. 

The main arguments are:

 * documentation can be placed above the function in the `R` file, documentation will be generated from that
 * Roxygen2 will manage `NAMESPACE` itself

If @thijsjanzen agrees, I volunteer to port the current LaTeX documentation to Roxygen2 style.

**Comment by thijsjanzen** [comment]
Agreed

**Comment by richelbilderbeek** [comment]
I close this issue, as the first step has been taken.
