### ISSUE TITLE
Suggestion: release v1.3

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/nLTT#11]
Current release is v1.2.1.
As the interface of a function has been changed, I suggest to have a new release on GitHub with version 1.3

@thijsjanzen : agree?

**Comment by thijsjanzen** [comment]
@richelbilderbeek: Agreed

Should we also push 1.3 to CRAN?

**Comment by richelbilderbeek** [comment]
I understood CRAN does not like new versions being delivered frequently and I have had no experience with them.

Personally, I'd say: yes, we should publish 1.3 to CRAN :+1:

**Comment by richelbilderbeek** [comment]
Due to #13 I suggest first to fix #13

**Comment by richelbilderbeek** [comment]
Waiting for an end user's review :hourglass_flowing_sand:

**Comment by thijsjanzen** [comment]
As far as I can see,  all code is now covered, and the vast majority of all code adheres to LintR.

recently, it appears that the number of downloads has decreased a little bit:

![zmc6ok1](https://cloud.githubusercontent.com/assets/19486664/18556470/ac98c3e6-7b6b-11e6-9844-6dfa41daac1b.png)

Let's boost the usage of nLTT!

**Comment by richelbilderbeek** [comment]
Yes, let's write an article using the nLTT statistics or so :-)

**Comment by thijsjanzen** [comment]
I have tried installing the devtools package on our cluster (in order to be able to install from GitHub), but unfortunately some dependencies of the devtools cluster fail to install... so no end-users experience here so far...

When installing locally using devtools, things seem to go allright, the command 
```"browseVignettes("nLTT")"``` works perfectly.
For some reason however, the function mcmc_nltt does appear to be elusive, and not accessible by the user. abc_smc_nltt (from the same *.R file) does work, and calculate_weight doesn't (but that one is explicitly marked as internal in nLTT-internal.Rd

**Comment by richelbilderbeek** [comment]
In case you want to make a private function public, to the Roxygen2 documentation, add

```
#' @export
```

to make it a public function.

In case it is about a function name alias, I did ruthlessly delete some of these when porting the documentation to Roxygen2. Perhaps the one you need needs to be added again.

**Comment by richelbilderbeek** [comment]
Fixed with commit 97165e658395ffc3c8893e1bc622abf85e4b63bf

**Comment by thijsjanzen** [comment]
I think everything seems to work - however, two Vignettes share the same name, and have a very similar introduction. Could you fix this @richelbilderbeek ?

**Comment by richelbilderbeek** [comment]
I will fix #16 on Monday.

**Comment by richelbilderbeek** [comment]
Fixed #16 , well done @richelbilderbeek !

**Comment by thijsjanzen** [comment]
Is there any progress here with the end-user experience? Otherwise I suggest we push the package to CRAN

**Comment by richelbilderbeek** [comment]
No progress in UX measurements. If you have the guts (I'd bet: yes, you have), do it :-)
