### ISSUE TITLE
v1.3 check errors

### ISSUE THREAD

**Issue by thijsjanzen** [richelbilderbeek/nLTT#12]
When checking the tar ball ("R CMD check --as-cran nLTT-1.3.tar.gz") I receive the following error:

checking package dependencies ... ERROR
Packages suggested but not available: ‘microbenchmark’ ‘rmarkdown’ ‘testit’

The suggested packages are required for a complete check.
Checking can be attempted without them by setting the environment
variable _R_CHECK_FORCE_SUGGESTS_ to a false value.

See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
manual.
* DONE

Also, I noticed that the version number in the DESCRIPTION file doesn't match the version number of the package (this I could correct myself, the others I'm unsure where to start, but you probably have a better idea about that @richelbilderbeek ).

**Comment by richelbilderbeek** [comment]
> Packages suggested but not available: ‘microbenchmark’ ‘rmarkdown’ ‘testit’

You'll have to install those packages on your local computer :sunglasses: 

>  the version number in the DESCRIPTION file doesn't match the version number of the package

Sure, you can have the honor of doing that

**Comment by thijsjanzen** [comment]
Yup, that was it...
