### ISSUE TITLE
Other users cannot use nLTT as they should

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/nLTT#13]
I've noticed at another user that

```
devtools::install_github("richelbilderbeek/nLTT")
library(nLTT)
??nLTT #does not produce the help!
vignette(package = "nLTT") #package not found
```

I am unsure why this is. As a first guess, I'd say 

 * [x] let Roxygen2 handle as much as possibe
 * [x] do a `devtools::build_vignette` (I noticed this sometimes caused my `.Rmd` vignette code to disappear)

@thijsjanzen : I suggest not to push to CRAN yet, and first have this fixed. Optional: can you confirm the same behavior at another end user?

**Comment by thijsjanzen** [comment]
This seems like an interesting problem. Unfortunately I have already pushed to CRAN.

**Comment by richelbilderbeek** [comment]
No problemo. OK if I try to fix it myself tomorrow?

**Comment by thijsjanzen** [comment]
Sure!

**Comment by richelbilderbeek** [comment]
Everything is handled by Roxygen2 now. 

I have observed differences myself.

I will test on an end-user later, yet assume it will work, thus closing this issue.
