### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by thijsjanzen** [richelbilderbeek/nLTT#14]
After submission I received the following feedback:

> We see
> 
> Change to non-FOSS package license.
> New license:
>   file LICENSE
> Old license:
>   GPL-2
> 
> We generally do not allow for such changes.

I suggest we change to instead of "file LICENSE" to put "GNU" (which is not non-FOSS)

**Comment by richelbilderbeek** [comment]
Well, the file LICENSE contains the GPL-2 license (and `lintr` made me do this change), and I expected this to be spotted by CRAN.

I suggest to change the license entry in DESCRIPTION to `GPL-2`.

**Comment by richelbilderbeek** [comment]
Done and works fine accoring to Travis.
