### ISSUE TITLE
Issues in testthat

### ISSUE THREAD

**Issue by thijsjanzen** [richelbilderbeek/nLTT#17]
It seems that after submission, three issues have popped up, found here: https://cran.r-project.org/web/checks/check_results_nLTT.html

```
being:
Result: NOTE 
    Package suggested but not available for checking: ‘microbenchmark’ 
Flavors: r-patched-solaris-sparc, r-patched-solaris-x86

```

@richelbilderbeek is microbenchmark necessary?

```
Version: 1.3 
Check: tests 
Result: ERROR 
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
     Generating Chain
     0--------25--------50--------75--------100
     *********************************************
     Finished MCMC.

     Generating Chain
     0--------25--------50--------75--------100
     *testthat results ================================================================
     OK: 103 SKIPPED: 0 FAILED: 1
     1. Error: get_average_nltt_matrix: speed comparison (@test_get_average_nltt_matrix.R#174) 

     Error: testthat unit tests failed
     Execution halted 
Flavors: r-patched-solaris-sparc, r-patched-solaris-x86
```

@richelbilderbeek: I think with updating to nltts_plot etc, some things have become broken somehow?

```
Version: 1.3 
Check: re-building of vignette outputs 
Result: WARN 
    Error in re-building vignettes:
     ...
    Warning: It seems you should call rmarkdown::render() instead of knitr::knit2html() because trees_with_root_edge.Rmd appears to be an R Markdown v2 document.
    Warning: It seems you should call rmarkdown::render() instead of knitr::knit2html() because vignette_get_nltt_values.Rmd appears to be an R Markdown v2 document.
    Loading required package: lattice
    Loading required package: survival
    Loading required package: Formula
    Loading required package: ggplot2

    Attaching package: 'Hmisc'

    The following object is masked from 'package:ape':

     zoom

    The following objects are masked from 'package:base':

     format.pval, round.POSIXt, trunc.POSIXt, units

    Quitting from lines 114-118 (vignette_get_nltt_values.Rmd) 
    Error: processing vignette 'vignette_get_nltt_values.Rmd' failed with diagnostics:
    the table must have a header (column names)
    Execution halted 
Flavors: r-patched-solaris-sparc, r-patched-solaris-x86
```

@richelbilderbeek can you check your vignette?

**Comment by thijsjanzen** [comment]
I wrote a new vignette btw, and found some errors in the manual, so I'm planning to submit version 1.3.1 very soon to CRAN - these errors can be caught then as well.

**Comment by richelbilderbeek** [comment]
> @richelbilderbeek is microbenchmark necessary?
Nope.

> @richelbilderbeek: I think with updating to nltts_plot etc, some things have become broken somehow?
It appears so

> @richelbilderbeek can you check your vignette?
I will tomorrow.

**Comment by thijsjanzen** [comment]
Line @test_get_average_nltt_matrix.R#174 involves:
```
timings <- microbenchmark::microbenchmark(

    nLTT::get_average_nltt_matrix_impl_1(treesim_phylogenies, dt = 0.1),
    nLTT::get_average_nltt_matrix_impl_2(treesim_phylogenies, dt = 0.01),
    times = 2
  )
  timings_summary <- summary(timings)
```

Apparently microbenchmark is not supported in solaris or so?
In [the manual of the microbenchmark package](https://cran.r-project.org/web/packages/microbenchmark/microbenchmark.pdf), they do report the following:

> One platform on which the clock resolution is known to be too low to measure short runtimes with the required precision is Oracle® Solaris on some SPARC® hardware. Reports of other platforms with similar problems are welcome. Please contact the package maintainer.

**Comment by richelbilderbeek** [comment]
Ah, it's a test to check which implementation is faster. I will remove the slower one, tomorrow :-)

**Comment by richelbilderbeek** [comment]
Alrighty, microbenchmarks are removed. I now try to reproduce the vignette error...

**Comment by richelbilderbeek** [comment]
I cannot reproduce the vignette error.

@thijsjanzen: How did you obtain it?

I've tried `devtools::build_vignettes()` but that works fine. Travis CI is -AFAIK- happy with my work as well.

**Comment by thijsjanzen** [comment]
I found them here @richelbilderbeek https://cran.r-project.org/web/checks/check_results_nLTT.html

**Comment by richelbilderbeek** [comment]
OK, I have increased the warning level of `vignette_get_nltt_values.Rmd` and got it to knit using `CTRL+K` without problems locally. `devtools::build_vignettes()` also works fine. I suggest to resubmit to CRAN if Travis CI is still OK...

**Comment by thijsjanzen** [comment]
I agree, we'll see if CRAN complains again. Should be fine though...

Alternatively, we could add "skip_on_cran()" flags?

**Comment by richelbilderbeek** [comment]
Well, the tests are fine now, so no need to skip those :sunglasses:  

Building the vignette `vignette_get_nltt_values.Rmd` is a problem I cannot reproduce locally nor on Travis! I am curious if I may already have fixed it :pray:

**Comment by richelbilderbeek** [comment]
So, will it be a go now?

**Comment by thijsjanzen** [comment]
I'll submit tonight

**Comment by richelbilderbeek** [comment]
Great! Let's see what happens this time :persevere:

**Comment by thijsjanzen** [comment]
It's on CRAN now, but the error remains: https://cran.r-project.org/web/checks/check_results_nLTT.html  (results for version 1.3.1)

Also, it seems something has gone horribly wrong with the file paths inside the tar ball - this might be due to me manually removing a number of files I found inside the tar ball that didn't need to be there...

**Comment by richelbilderbeek** [comment]
Blimey, those *are* some impressive paths! My favorite is `
nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/nLTT/tests/testthat`, because it is the longest.

I will try again to fix it now.

**Comment by richelbilderbeek** [comment]
The warning ...

```
checking re-building of vignette outputs ... WARNING
Error in re-building vignettes:
  ...
Warning: It seems you should call rmarkdown::render() instead of knitr::knit2html() because trees_with_root_edge.Rmd appears to be an R Markdown v2 document.
Error: processing vignette 'vignette_get_nltt_values.Rmd' failed with diagnostics:
(converted from warning) It seems you should call rmarkdown::render() instead of knitr::knit2html() because vignette_get_nltt_values.Rmd appears to be an R Markdown v2 document.
Execution halted
```

... is caused by Pandoc being absent on the build computer, as described [here](https://github.com/yihui/knitr/issues/1286). Thus, I cannot be blamed on that.

I will check the other one now.

**Comment by thijsjanzen** [comment]
Given that they are warnings, I don't see any pressing reasons to fix this ASAP.

**Comment by richelbilderbeek** [comment]
Agree, we even do not have the :zap: to fix the pandoc error. The `the table must have a header (column names)` error I will postpone :smiley: .

**Comment by thijsjanzen** [comment]
It seems the weird path error has disappeared from the error page: https://cran.r-project.org/web/checks/check_results_nLTT.html

Only the Solaris error (which can't be fixed) and the knitr/markdown error remain

**Comment by richelbilderbeek** [comment]
Looks like we are as clean as can be now :v:

**Comment by richelbilderbeek** [comment]
Looks like this has been done :-)
