### ISSUE TITLE
Suggestion: have a develop branch

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/nLTT#18]
To ensure the stability of nLTT, I suggest to add a `develop` branch. [Here](https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows) is the more detailed version of what I mean :-)

I suggest to set this repo to `master` branch by default for our users.

**Comment by thijsjanzen** [comment]
Sounds good! This is exactly where my Git knowledge starts to taper off, so I'm happy if you can take care of this @richelbilderbeek

**Comment by richelbilderbeek** [comment]
I will, probably this week. I will also document the new workflow, so any developer should be able to  follow easily. I suggest you will ask for clarifications if needed :vulcan_salute:

**Comment by richelbilderbeek** [comment]
Better idea: I will create a develop branch after #17 has been resolved and the submission to CRAN has been completed.

**Comment by richelbilderbeek** [comment]
I took the liberty of adding a develop branch.

Usage to get to `develop` branch:

```
git checkout develop
```

**Comment by richelbilderbeek** [comment]
Done!
