### ISSUE TITLE
Satisfy lintrbot

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/nLTT#19]
When building the vignettes, with `devtools::build_vignettes()` from within R, then `./clean_vignettes.sh` from the CLI, [lintr-bot has some complaints about the walkthrough vignette](https://github.com/richelbilderbeek/nLTT/commit/8a03561b6947e8b5d7c53af16cdcb75f9975a1f7#commitcomment-19345954). 

Tip: you can silence a warning that cannot be fixed (e.g. `library(nLTT)`) with `# nolint`

**Comment by thijsjanzen** [comment]
Fixed the previous issues, but it seems that ./clean_vignettes.sh doesn't work so well here locally (macOS Sierra).
It generates several weird files (e.g. alkthrough.R), and doesn't seem to remove the white spaces..

**Comment by thijsjanzen** [comment]
something is wrong with the vignette files, perhaps due to ./clean_vignettes.sh

I got the following feedback from CRAN:

> We see
> 
> Files in the 'vignettes' directory newer than same file in 'inst/doc':
>   'vignette_get_nltt_values.Rmd'
> 
> and in fact the two files are different.  Could you please remove the one you don't want?

**Comment by richelbilderbeek** [comment]
Did you forget to do `devtools::build_vignettes()` to create the files in `inst/doc`? Because if not, they are right :-)

**Comment by thijsjanzen** [comment]
I don't think so. I rebuild them though, and ran the .sh file, and got the following errors:

```
alkthrough.R
sed: -e: No such file or directory
sed: 1: "alkthrough.R": command a expects \ followed by text
trees_with_root_edge.R
sed: -e: No such file or directory
sed: 1: "trees_with_root_edge.R": undefined label 'rees_with_root_edge.R'
vignette_get_average_nltt.R
sed: -e: No such file or directory
sed: 1: "vignette_get_average_nl ...": invalid command code v
vignette_get_nltt_values.R
sed: -e: No such file or directory
sed: 1: "vignette_get_nltt_values.R": invalid command code v
vignette_nltts_plot.R
sed: -e: No such file or directory
sed: 1: "vignette_nltts_plot.R": invalid command code v
vignette_stretch_nltt_matrix.R
sed: -e: No such file or directory
sed: 1: "vignette_stretch_nltt_m ...": invalid command code v
walkthrough.R
sed: -e: No such file or directory
sed: -i may not be used with stdin
```

**Comment by richelbilderbeek** [comment]
It *is* weird that the files get modified. I can take a look at it tomorrow, but if really want me I can be forced to take a look today.

**Comment by thijsjanzen** [comment]
Tomorrow is fine

**Comment by richelbilderbeek** [comment]
The script worked fine on multiple GNU/Linux computers. It was easiest to just fix your typos.
