### ISSUE TITLE
Build Error, package dependency on package 'survival' by package 'Hmisc'

### ISSUE THREAD

**Issue by thijsjanzen** [richelbilderbeek/nLTT#20]
> Error : package ‘survival’ 2.39.4 was found, but >= 2.40.1 is required by ‘Hmisc’
> ERROR: lazy loading failed for package ‘Hmisc’

Do we need the package Hmisc?

**Comment by richelbilderbeek** [comment]
I do use it, but I'd prefer to remove it to get rid of this dependency problem.

**Comment by richelbilderbeek** [comment]
I'll fix it now

**Comment by richelbilderbeek** [comment]
Fixed!
