### ISSUE TITLE
Test 'abc_smc_nltt use' fails

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/nLTT#26]
Last commit that works: c3e44977d5f7cd3b0a223cfce914c312090bfdf3

I think this is due to a changed `nLTTstat_exact` function.

**Comment by richelbilderbeek** [comment]
* Copied the original `nLTTstat_exact` function, 
 * named it as `nLTTstat_exact_classic`
 * Let the test 'abc_smc_nltt use' use that one instead

Fails just the same!

Would there be a back-end problem?

**Comment by richelbilderbeek** [comment]
Oops.

**Comment by richelbilderbeek** [comment]
Experiment: re-run older successful version!

Before: 
![before](https://cloud.githubusercontent.com/assets/2098230/22247169/ac154e92-e238-11e6-84ab-7acda94ac550.png)

**Comment by richelbilderbeek** [comment]
Yuck, that one fails due to `HMisc` being absent. Tme to Go Back In Time and create a branch called 'patch-26'.

**Comment by richelbilderbeek** [comment]
Older version also fails:

![after](https://cloud.githubusercontent.com/assets/2098230/22247766/bfcc4596-e23b-11e6-84d0-7557ea5986c8.png)

**Comment by richelbilderbeek** [comment]
Also locally, the old version fails:

![localerror](https://cloud.githubusercontent.com/assets/2098230/22248253/ffb3f544-e23d-11e6-9318-233a9360f69f.png)

**Comment by richelbilderbeek** [comment]
@thijsjanzen : it appears something has changed beyond the scope of our GitHub

I can fix this by replacing

```
testthat::expect_equal(
    mean(A),
    ML$minimum[[1]],
    tolerance = 0.05
  )
```

by 

```
testthat::expect_equal(
    mean(A),
    ML$minimum[[1]],
    tolerance = 0.052 # Higher tolerance
  )
```

Do I have a go?

**Comment by thijsjanzen** [comment]
I'm unsure why this fails, but a tolerance of 0.052 seems reasonable (however, with the same seeds, this should never fail).
Also, can't the HMisc issue be solved other than reverting to an old version?

**Comment by richelbilderbeek** [comment]
OK, I'll increase the tolerance.

Fixing `Hmisc` is just removing it from `DESCRIPTION`.

**Comment by thijsjanzen** [comment]
Feel free to transition the package to packrat @richelbilderbeek  :D
