### ISSUE TITLE
Add CONTRIBUTING

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/nLTT#29]
It is A Good Idea [no reference out of the top of my head] to add [a CONTRIBUTING file](https://github.com/richelbilderbeek/pbdmms/blob/master/CONTRIBUTING.md). It stimulates others to contribute.

I suggest to do so. I volunteer to write a first draft.

**Comment by thijsjanzen** [comment]
Sure, go ahead!

**Comment by richelbilderbeek** [comment]
First draft is there.
