### ISSUE TITLE
panDoc related errors

### ISSUE THREAD

**Issue by thijsjanzen** [richelbilderbeek/nLTT#35]
From the CRAN package check results: https://cran.r-project.org/web/checks/check_results_nLTT.html

> Version: 1.3.1 
Check: re-building of vignette outputs 
Result: WARN 
    Error in re-building vignettes:
     ...
    Warning in engine$weave(file, quiet = quiet, encoding = enc) :
     Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
    Error: processing vignette 'vignette_get_nltt_values.Rmd' failed with diagnostics:
    (converted from warning) Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
    Execution halted 
Flavors: r-patched-solaris-sparc, r-patched-solaris-x86, r-release-osx-x86_64

Also

> Version: 1.3.1 
Check: re-building of vignette outputs 
Result: WARN 
    Error in re-building vignettes:
     ...
    Warning: It seems you should call rmarkdown::render() instead of knitr::knit2html() because trees_with_root_edge.Rmd appears to be an R Markdown v2 document.
    Error: processing vignette 'vignette_get_nltt_values.Rmd' failed with diagnostics:
    (converted from warning) It seems you should call rmarkdown::render() instead of knitr::knit2html() because vignette_get_nltt_values.Rmd appears to be an R Markdown v2 document.
    Execution halted 
Flavor: r-oldrel-osx-x86_64

**Comment by richelbilderbeek** [comment]
Note to self:

From [https://www.rdocumentation.org/packages/knitr/versions/1.12.3/topics/vignette_engines](https://www.rdocumentation.org/packages/knitr/versions/1.12.3/topics/vignette_engines) I quote:

```
If you use the knitr::rmarkdown engine, please make sure that you put rmarkdown in the Suggests field of your DESCRIPTION file.
```

**Comment by richelbilderbeek** [comment]
Hmm, `rmarksdown` *is* already in the `Suggests`.

**Comment by richelbilderbeek** [comment]
Added `Hmisc` in `Suggests`, as I got the error that `Hmisc` was missing when knitting the vignette.

**Comment by richelbilderbeek** [comment]
Problem: keep `.R` and `.Rmd` files in `vignette` folder.

**Comment by richelbilderbeek** [comment]
Maybe fixed it, need to look at CRAN link later.

**Comment by thijsjanzen** [comment]
Sure, I can upload it! I think there have been a lot of updates recently as well.
What should we do with the version number?

**Comment by richelbilderbeek** [comment]
1.4 would be fine @thijsjanzen :+1:

**Comment by thijsjanzen** [comment]
Dear maintainer,
 
thanks, package nLTT_1.4.tar.gz is on its way to CRAN now.
 
Best regards,
CRAN teams' auto-check service

**Comment by thijsjanzen** [comment]
Some issues remain:

> Version: 1.4 
> Check: dependencies in R code 
> Result: NOTE 
>     Namespace in Imports field not imported from: ‘deSolve’
>      All declared Imports should be used. 
> Flavors: r-devel-linux-x86_64-fedora-clang, r-devel-linux-x86_64-fedora-gcc, r-devel-osx-x86_64, r-patched-solaris-x86, r-release-osx-x86_64
> 

> Version: 1.4 
> Check: re-building of vignette outputs 
> Result: WARN 
>     Error in re-building vignettes:
>      ...
>     Warning in engine$weave(file, quiet = quiet, encoding = enc) :
>      Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
>     Warning in engine$weave(file, quiet = quiet, encoding = enc) :
>      Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
>     Warning in engine$weave(file, quiet = quiet, encoding = enc) :
>      Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
>     Warning in engine$weave(file, quiet = quiet, encoding = enc) :
>      Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
>     Warning in engine$weave(file, quiet = quiet, encoding = enc) :
>      Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
>     Error: processing vignette 'walkthrough.Rmd' failed with diagnostics:
>     (converted from warning) Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
>     Execution halted 
> Flavors: r-devel-osx-x86_64, r-patched-solaris-x86, r-release-osx-x86_64
> 

oddly, these issues did not pop up when building and checking --as-cran on my macbook (I guess my maxOS is a different version)

**Comment by richelbilderbeek** [comment]
Indeed, [Travis thinks it is OK](https://travis-ci.org/richelbilderbeek/nLTT/jobs/368057130#L1329), [AppVeyor thinks it is OK](https://ci.appveyor.com/project/richelbilderbeek/nLTT/branch/master#L270), my computer thinks so as well.

Does this stop the CRAN submission? If yes, will look into this on Saturday

**Comment by thijsjanzen** [comment]
No, version 1.4 is on CRAN, no issues with the CRAN maintainers.

**Comment by richelbilderbeek** [comment]
No hurries then :+1:

**Comment by richelbilderbeek** [comment]
Close this Issue, things work on Travis in three build environments :+1:
