### ISSUE TITLE
New random number generator on CRAN

### ISSUE THREAD

**Issue by thijsjanzen** [richelbilderbeek/nLTT#41]
> Dear maintainer,
> 
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_nLTT.html>.
> 
> The check problems with current R-devel are from
> 
>      • The default method for generating from a discrete uniform
>        distribution (used in sample(), for instance) has been changed.
>        ...
>        The previous method can be requested using RNGkind() or
>        RNGversion() if necessary for reproduction of old results.
> 
> To make your package successfully pass the checks for current R-devel
> and R-release you may find it most convenient to insert
> 
>   suppressWarnings(RNGversion("3.5.0"))
> 
> before calling set.seed() in your example, vignette and test code (where
> the difference in RNG sample kinds matters, of course).
> 
> Note that this ensures using the (old) non-uniform "Rounding" sampler
> for all 3.x versions of R, and does not add an R version dependency.
> Note also that the new "Rejection" sampler which R will use from 3.6.0
> onwards by default is definitely preferable over the old one, so that
> the above should really only be used as a temporary measure for
> reproduction of the previous behavior (and the run time tests relying on
> it).
> 
> Please correct before 2019-03-20 to safely retain your package on CRAN.
> 
> Best,
> -k

**Comment by thijsjanzen** [comment]
I don't really understand what needs to be done though...

**Comment by thijsjanzen** [comment]
I have added 'suppressWarnings(RNGversion("3.5.0"))' where applicable (as far as I can see). 

I don't know how to check the package using the new R version, so I can't test whether what I did resolves the issues provided. You surely know @richelbilderbeek ?

**Comment by richelbilderbeek** [comment]
Yes, it's already fixed :+1:

**Comment by thijsjanzen** [comment]
I have removed all the suppressWarnings(RNGversion("3.5.0") additions I made previously. I do not see any changes in behaviour.

**Comment by richelbilderbeek** [comment]
Wouldn't it be fixed already?

To [quote myself](https://github.com/richelbilderbeek/nLTT/issues/41#issuecomment-471537343):

> [...] it's already fixed +1
