### ISSUE TITLE
Fix ABC issue in 'Walkthrough' vignette

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/nLTT#43]
[Here](https://github.com/richelbilderbeek/nLTT/blob/master/vignettes/walkthrough.Rmd#L117) I if-fed out some code that caused the Travis build to fail.

As this is the part of @thijsjanzen, I suggest he fixes it. Good luck :+1:

**Comment by thijsjanzen** [comment]
This is an issue with TESS - I'm changing the example bd-tree simulator to the sim.bd.taxa.age function in TreeSim.

**Comment by thijsjanzen** [comment]
Fixed now by using sim.bd.taxa.age from TreeSim
