### ISSUE TITLE
Submitting to CRAN

### ISSUE THREAD

**Issue by thijsjanzen** [richelbilderbeek/nLTT#46]
Upon submitting to CRAN, I receive the following error:

> Could not determine maintainer email, please correct the DESCRIPTION file or contact the CRAN team

Alternatively, after switching to the master branch and locally building the tarball, and subsequently running `R CMD check --as-cran nLTT_1.4.tar.gz `, I receive the following errors (which somehow don't show up on Travis)

```
* checking examples ... WARNING
checking a package with encoding  'UTF-8'  in an ASCII locale

* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
  Running 'testthat.R'
 ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  1/1 mismatches
  [1] 0.138 - 0.105 == 0.0333
  
  -- 2. Failure: squ nLTTstat on known tree (@test-nLTTstat.R#36)  ---------------
  0.02407742 not equal to nLTTstat(tree1 = p, tree2 = q, distance_method = "squ").
  1/1 mismatches
  [1] 0.0241 - 0.0165 == 0.00753
  
  == testthat results  ===========================================================
  OK: 123 SKIPPED: 3 WARNINGS: 0 FAILED: 2
  1. Failure: abs nLTTstat on known tree (@test-nLTTstat.R#25) 
  2. Failure: squ nLTTstat on known tree (@test-nLTTstat.R#36) 
  
  Error: testthat unit tests failed
  Execution halted

```

I don't understand...

**Comment by richelbilderbeek** [comment]
* Travis may use a different version than your local computer. Currently, Travis builds for MacOS and Linux (both `r-devel` and `r-release`)
 * I've seen that on AppVeyor the Windows build fails, no idea why

**Comment by thijsjanzen** [comment]
> * I've seen that on AppVeyor the Windows build fails, no idea why
See Issue #45

**Comment by richelbilderbeek** [comment]
Test is fixed!

Perhaps you need to contact @rsetienne, as [DDD needs R 3.6.0, but can live fine without it](https://github.com/rsetienne/DDD/pull/8).

**Comment by thijsjanzen** [comment]
Submitted to CRAN

**Comment by richelbilderbeek** [comment]
Cool, :crossed_fingers:

**Comment by thijsjanzen** [comment]
> > Thanks, on its way to CRAN.
> 
> Best,
> Uwe Ligges
