### ISSUE TITLE
Write test for ABC_SMC

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/nLTT#7]
When I take a look at the code coverage, I see ABC_SMC is not tested at all:

![codecov](https://cloud.githubusercontent.com/assets/2098230/17103789/57bddc9e-5280-11e6-8834-1e3f6ec89d75.png)

There was no example code anywhere, so I cannot write this test.

Would these tests be written, code coverage will increase. Code coverage is known to correlate with code quality [1], so now the nLTT package is underestimated.

I hope @thijsjanzen can do that.

## References

[1] Del Frate, Fabio and Garg, Praerit and Mathur, Aditya P and Pasquini, Alberto, "On the correlation between code coverage and software reliability", in Software Reliability Engineering, 1995. Proceedings., Sixth International Symposium on (, 1995), pp. 124--132.

**Comment by thijsjanzen** [comment]
Partially done - I have added some abuse tests, haven't been able to do a usage test - find a simple case in which we can easily use ABC-SMC and know the expected results. I will get back to that.

**Comment by richelbilderbeek** [comment]
Awesome! Let's go for that 100% code coverage :sunglasses:

**Comment by thijsjanzen** [comment]
Done, 100% reached!
