### ISSUE TITLE
nLTT statistic does not take stem into account

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/nLTT#9]
From the vignette `trees_with_root_edge.Rmd`:

![issue](https://cloud.githubusercontent.com/assets/2098230/18436268/c9150618-78f7-11e6-890d-1eda7b67b3f9.png)

@thijsjanzen : do you agree this behavior is incorrect? If yes, I volunteer to fix it.

**Comment by thijsjanzen** [comment]
This behaviour is incorrect, but I'm unsure what types of trees p and q are?

**Comment by richelbilderbeek** [comment]
This is how they are created:

```
set.seed(42)
p <- ape::rcoal(4)
q <- p
q$root.edge <- 5
```

**Comment by thijsjanzen** [comment]
Ah! Dus de plot is incorrect, en niet de nLTT statistic - aangenomen dat 
de nLTT statistic altijd van crown age uitgaat.

Wellicht moeten we hier een paar checks voor inbouwen, zodat de twee 
trees die worden vergeleken in gelijke mate geroot zijn... (immers kan 
men ook 2 trees vergelijken die beiden geroot zijn, dat hoeft geen 
probleem te zijn, mits de gebruiker daar behoefte aan heeft).

**Comment by richelbilderbeek** [comment]
I think the plot *is* correct, as I think it is natural to assume that `a tree without a root` == `a tree with a root length of zero`. I think the nLTT statistic should take the root lengths into account, unless you disagree (you are the authority here :sunglasses: ).

**Comment by richelbilderbeek** [comment]
One backwards-compatible fix may be:

```
nLTTstat_exact(p, q, from = "crown")
```

where `from` may also be `root`.

This does not have my preference, as I cannot see why the nLTT statistic would ignore stems. But again, you are the authority here :rainbow:

**Comment by thijsjanzen** [comment]
You are right, the plot is correct, and the nLTT function is incorrect. Off the top of my head I'm not entirely sure how to change the code to incorporate the root - the branching times function of ape doesn't have any extra flags... we could try and add the root time to the branching times vector?

I like the idea of an extra from argument, as this also makes it for the user more explicit what is going on.

**Comment by richelbilderbeek** [comment]
Let me fix that function, you'll see :sunglasses: 

I am not a fan of adding the extra argument, as it just makes the natural assumption ('stems are also tracked') explicit, at the cost of making the user interface more complex. OTOH, I am not impressed by my own reasoning myself and I think both options (adding an extra argument yes/no) are close to equally good.

But, unless you change your mind (that there need not be an extra function argument), I will fix this tomorrow, with the extra argument.
